apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobber-postgres
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobber-postgres
  template:
    metadata:
      labels:
        app: jobber-postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: jobber-postgres
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: jobber
        - name: POSTGRES_PASSWORD
          value: api
        - name: POSTGRES_DB
          value: jobber_reviews
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: jobber-postgres
          containerPort: 5432
        volumeMounts:
        - name: postgres-local-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        readinessProbe:
          exec:
            command: ["psql", "-w", "-U", "jobber", "-d", "jobber_reviews", "-c", "SELECT 1"]
          initialDelaySeconds: 120
          periodSeconds: 300
          timeoutSeconds: 60
        livenessProbe:
          exec:
            command: ["psql", "-w", "-U", "jobber", "-d", "jobber_reviews", "-c", "SELECT 1"]
          initialDelaySeconds: 120
          periodSeconds: 300
          timeoutSeconds: 60
      volumes:
      - name: postgres-local-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

